/* 
 * CyberSource Flex API
 *
 * Simple PAN tokenization service
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CyberSource.Api;
using CyberSource.Model;
using CyberSource.Client;
using System.Reflection;

namespace CyberSource.Test
{
    /// <summary>
    ///  Class for testing CreateInstrumentIdentifierRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateInstrumentIdentifierRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateInstrumentIdentifierRequest
        //private CreateInstrumentIdentifierRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateInstrumentIdentifierRequest
            //instance = new CreateInstrumentIdentifierRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateInstrumentIdentifierRequest
        /// </summary>
        [Test]
        public void CreateInstrumentIdentifierRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateInstrumentIdentifierRequest
            //Assert.IsInstanceOfType<CreateInstrumentIdentifierRequest> (instance, "variable 'instance' is a CreateInstrumentIdentifierRequest");
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property '_Object'
        /// </summary>
        [Test]
        public void _ObjectTest()
        {
            // TODO unit test for the property '_Object'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Card'
        /// </summary>
        [Test]
        public void CardTest()
        {
            // TODO unit test for the property 'Card'
        }
        /// <summary>
        /// Test the property 'BankAccount'
        /// </summary>
        [Test]
        public void BankAccountTest()
        {
            // TODO unit test for the property 'BankAccount'
        }
        /// <summary>
        /// Test the property 'ProcessingInformation'
        /// </summary>
        [Test]
        public void ProcessingInformationTest()
        {
            // TODO unit test for the property 'ProcessingInformation'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
